spring:
  profiles:
    active: usage_message
  application:
    name: rabbittut


logging:
  level:
    org: INFO

tutorial:
  client:
    duration: 600000

security:
  basic:
    enabled: false

management:
  security:
    enabled: false